site_name: home-automation
theme:
    name: readthedocs
    highlightjs: true
nav:
  - Home: 'index.md'
  - 'Hardware':
    - 'Allgemein': 'hardware/allgemein.md'
    - 'DS2408 Board': 'hardware/ds2408/index.md'
    - 'DS2408 Zusatz': 'hardware/ds2408_zusatz/index.md'
    - 'MCP23017 Board': 'hardware/mcp23017/index.md'
    - 'DS2438 Feuchte': 'hardware/ds2438/index.md'
    - 'Lüftung': 'hardware/lueftung.md'
  - 'Software':
    - 'Allgemein': 'software/index.md'
    - 'OneWire': 'software/oneWire.md'
    - 'i2c': 'software/i2c.md'
    - 'Home Assistant': 'software/hass.md'
    - 'Entwicklerwerkzeuge': 'software/development.md'
    