esphome:
  name: zisterne

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Zisterne Fallback Hotspot"
    password: "dWXqcoUuXQl4"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin: 5

sensor:
  - platform: htu21d
    temperature:
      name: "Outside Temperature"
    humidity:
      name: "Outside Humidity"
    update_interval: 20s
  - platform: ultrasonic
    trigger_pin: GPIO19
    echo_pin: GPIO18
    name: "Water Level"
    icon: "mdi:water"
    update_interval: 10s
    # Maximale Entfernung
    timeout: 3m
    filters:
    - filter_out: nan
#    - lambda: return 6.00-x; # 6.00 is the distance between the sensor and the bottom of the tank