version: '3'
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /home/lasve/workspace/home-automation/ESPHomeProjects:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host