esphome:
  name: hydro1

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hydro1 Fallback Hotspot"
    password: "UqML9IAP2Bw5"

captive_portal:

i2c:
  # I2C fuer Helligkeitssensor
  - id: bus_a
    sda: 16
    scl: 17
    scan: true
  # I2C fuer Helligkeitssensor
  - id: bus_b
    sda: 33
    scl: 32
    frequency: 10000
    scan: true

switch:
  # Zeit zum Beleuchten
  - platform: template
    name: "Beleuchtungszeit"
    id: beleuchtungszeit_swi
    turn_on_action:
      # homeassistant mitteilen, dass der Schalter jetzt an ist.
      - switch.template.publish:
          id: beleuchtungszeit_swi
          state: ON
    turn_off_action:
      # homeassistant mitteilen, dass der Schalter jetzt aus ist.
      - switch.template.publish:
          id: beleuchtungszeit_swi
          state: OFF
      - switch.turn_off: beleuchtung_swi 
  - platform: gpio
    name: "Pflanz-Pumpe"
    id: pumpe_swi
    pin: 5
    inverted: true
  - platform: gpio
    name: "Pflanz-Licht"
    id: beleuchtung_swi
    pin: 18
    inverted: true

sensor:
  # Wasserstand
  - platform: vl53l0x
    name: "Wasserstand"
    id: hydro_level
    address: 0x29
    update_interval: 10s
    long_range: false
    i2c_id: bus_b
  # Helligkeit
  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    measurement_duration: 69
    update_interval: 60s
    i2c_id: bus_a
    on_value:
      then:
        - if:
            condition:
              and:
                - lambda: 'return x<1000;'
                - switch.is_on: beleuchtungszeit_swi
                - switch.is_off: beleuchtung_swi
            then:
              - logger.log: "Zu Dunkel, schalte Licht ein."
              - switch.turn_on: beleuchtung_swi
        - if:
            condition:
              and:
                - lambda: 'return x>2000;'
                - switch.is_on: beleuchtungszeit_swi
                - switch.is_on: beleuchtung_swi
            then:
              - logger.log: "Hell genug, schalte Licht aus."
              - switch.turn_off: beleuchtung_swi        
    #on_value_range:
    ##Aktiviert nur, wenn Wert tatsaechlich von ausserhalb zu innerhalb des Bereiches wechselt
    #  - above: 250
    #    then:
    #      - if:
    #          condition:
    #            and:
    #              - switch.is_on: beleuchtung_swi
    #              - switch.is_on: beleuchtungszeit_swi
    #          then:
    #            - switch.turn_off: beleuchtung_swi
    #  - below: 200
    #    then:
    #      - if:
    #          condition:
    #            and:
    #              - switch.is_off: beleuchtung_swi
    #              - switch.is_on: beleuchtungszeit_swi
    #          then:
    #            - switch.turn_on: beleuchtung_swi

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      # Beleuchtungszeit aktivieren
      - seconds: 0
        minutes: 0
        hours: 8
        then:
          - switch.turn_on: beleuchtungszeit_swi
      # Beleuchtungszeit deaktivieren
      - seconds: 0
        minutes: 30
        hours: 21
        then:
          - switch.turn_off: beleuchtungszeit_swi
      # Pumpe einschalten (alle halbe Stunde)
      - seconds: 0
        minutes: /30
        hours: 8-20
        then:
          - switch.turn_on: pumpe_swi
      # Pumpe ausschalten (nach 5 Min)
      - seconds: 0
        minutes: 5/30
        hours: 8-21
        then:
          - switch.turn_off: pumpe_swi
      
