- platform: generic_thermostat
  name: Arbeitszimmer
  heater: switch.29_c10437000000_pio_2
  target_sensor: sensor.28_ff9a3a501603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Wohnzimmer
  heater: switch.29_c10437000000_pio_3
  target_sensor: sensor.28_ff380fb41603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Kueche
  heater: switch.29_c10437000000_pio_4
  target_sensor: sensor.28_ffcbed531604_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: WCEG
  heater: switch.29_c10437000000_pio_5
  target_sensor: sensor.28_ff5304511603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: WCOG
  heater: switch.29_c10437000000_pio_6
  target_sensor: sensor.28_ffc27cb41603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Bibo
  heater: switch.29_c10437000000_pio_7
  target_sensor: sensor.28_ffe302511603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 20.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Ankleide
  heater: switch.29_b90437000000_pio_0
  target_sensor: sensor.28_ff0dcf501603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 18.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Sina
  heater: switch.29_b90437000000_pio_1
  target_sensor: sensor.28_ff0f3e541604_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 21.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Malte
  heater: switch.29_b90437000000_pio_2
  target_sensor: sensor.28_ff3b2a511603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Schlafzimmer
  heater: switch.29_b90437000000_pio_3
  target_sensor: sensor.28_ff3bc3471603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 18.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Studio
  heater: switch.29_b90437000000_pio_5
  target_sensor: sensor.28_ff5ad9501603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: Galerie
  heater: switch.29_b90437000000_pio_4
  target_sensor: sensor.28_ff4777b41603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 20.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: HandtuchEG
  heater: switch.29_b90437000000_pio_6
  target_sensor: sensor.28_ff5304511603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1
- platform: generic_thermostat
  name: HandtuchOG
  heater: switch.29_b90437000000_pio_7
  target_sensor: sensor.28_ffc27cb41603_temperature
  min_temp: 16
  max_temp: 26
  ac_mode: false
  target_temp: 22.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 1
  initial_hvac_mode: "heat"
  away_temp: 16
  precision: 0.1