
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Test generic thermostat
climate: !include climate.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# https://www.home-assistant.io/integrations/rest_command/
rest_command:
  rollosteuerung:
    method: POST
    url: http://hwr.local:5000/Shutters
    payload: '{"cmd": "{{ cmd }}","window": "{{ window }}","time": "{{ time }}"}'
    content_type: 'application/json; charset=utf-8'

# https://www.home-assistant.io/integrations/cover.template/
cover:
  - platform: template
    covers:
      rollo_arbeit:
        friendly_name: "Rollo Arbeitszimmer"
        position_template: "50"
        open_cover:
          service: rest_command.rollosteuerung
          data:
            cmd: "open"
            window: 1
            time: 10
        close_cover:
          service: rest_command.rollosteuerung
          data:
            cmd: "close"
            window: 1
            time: 5
        stop_cover:
          service: rest_command.rollosteuerung
          data:
            cmd: "stop"
            window: 1
      fenstertestrollo:
        friendly_name: "Fenster Rollo Test"
        position_template: "50"
        open_cover:
          service: rest_command.rollosteuerung
          data:
            cmd: "open"
            window: 12
            time: 10
        close_cover:
          service: rest_command.rollosteuerung
          data:
            cmd: "close"
            window: 12
            time: 5
        stop_cover:
          service: rest_command.rollosteuerung
          data:
            cmd: "stop"
            window: 12

# Modul 1
#  name: ArbeitUp
#  name: ArbeitDown
#  name: WohnOstUp
#  name: WohnOstDown
#  name: WohnSuedUp
#  name: WohnSuedDown
#  name: WohnTuerUp
#  name: WohnTuerDown
# Modul 2
#  name: KuecheTuerUp
#  name: KuecheTuerDown
#  name: KuecheSuedUp
#  name: KuecheSuedDown
#  name: KuecheWestUp
#  name: KuecheWestDown
#  name: WCEGUp
#  name: WCEGDown
# Modul 3
#  name: HWRUp
#  name: HWRDown
#  name: TreppeUp
#  name: TreppeDown
#  name: MalteNordUp
#  name: MalteNordDown
#  name: MalteOstUp
#  name: MalteOstDown
# Modul 4
#  name: SinaOstUp
#  name: SinaOstDown
#  name: SinaSuedUp
#  name: SinaSuedDown
#  name: BiboUp
#  name: BiboDown
#  name: WCOGSuedUp
#  name: WCOGSuedDown
# Modul 5
#  name: WCOGWestUp
#  name: WCOGWestDown
#  name: SchlafenUp
#  name: SchlafenDown

# Connect to Vitodens 300 with Vitotronic 200 via vicare integration
vicare:
  username: !secret vicare_user
  password: !secret vicare_pass
  client_id: !secret vicare_id
  name: ViCare

# Altes esersa Geraet
#    switch.29_ae571a000000_pio_0:
#      friendly_name: Erz_Arbeiten
#    switch.29_ae571a000000_pio_1:
#      friendly_name: Erz_Wohnen_Ecke
#    switch.29_ae571a000000_pio_2:
#      friendly_name: Erz_Kueche
#    switch.29_ae571a000000_pio_3:
#      friendly_name: Erz_Bibo
#    switch.29_ae571a000000_pio_4:
#      friendly_name: Erz_Schlafen
#    switch.29_ae571a000000_pio_5:
#      friendly_name: Erz_Galerie
#    switch.29_ae571a000000_pio_6:
#      friendly_name: Erz_Studio


# Convert auto generated 1-Wire device ids into friendly names 
homeassistant:
  customize:
    switch.29_ad0837000000_pio_0:
      friendly_name: "Arbeitszimmer Fenster (11)"
    switch.29_ad0837000000_pio_1:
      friendly_name: "Wohnzimmer Ecke (13)"
    switch.29_ad0837000000_pio_2:
      friendly_name: "15 oder 16"
    switch.29_ad0837000000_pio_3:
      friendly_name: "Küche Terrassentür (18)"
    switch.29_ad0837000000_pio_4:
      friendly_name: "Malte Ost (21)"
    switch.29_ad0837000000_pio_5:
      friendly_name: "Malte Nord (22)"
    switch.29_ad0837000000_pio_6:
      friendly_name: "Bibliothek Fenster (30)"
    switch.29_ad0837000000_pio_7:
      friendly_name: "Sina Fenster Bibo (31)"
    switch.29_b20837000000_pio_0:
      friendly_name: "Sina Fenster Ecke (32)"
    switch.29_b20837000000_pio_1:
      friendly_name: "Schlafzimmer Fenster (33)"
    switch.29_b20837000000_pio_2:
      friendly_name: "Schlafzimmer Sven (34)"
    switch.29_b20837000000_pio_3:
      friendly_name: "Schlafzimmer Mandy (35)"
    switch.29_b20837000000_pio_4:
      friendly_name: "Gallerie Dachfenster (36)"
    switch.29_b20837000000_pio_5:
      friendly_name: "Gallerie Fenster (37)"
    switch.29_b20837000000_pio_6:
      friendly_name: "Studio Fenster (38)"
    switch.29_b20837000000_pio_7:
      friendly_name: "Zirkulationspumpe"
    switch.29_330214000000_pio_0:
      friendly_name: FBH_ANKL
    switch.29_330214000000_pio_1:
      friendly_name: FBH_KID2
    switch.29_330214000000_pio_2:
      friendly_name: FBH_KID1
    switch.29_330214000000_pio_3:
      friendly_name: FBH_SCHL
    switch.29_330214000000_pio_4:
      friendly_name: FBH_STUD
    switch.29_330214000000_pio_5:
      friendly_name: FBH_GALE
    switch.29_330214000000_pio_6:
      friendly_name: FBH_WCEG_H
    switch.29_330214000000_pio_7:
      friendly_name: FBH_WCOG_H  
    sensor.28_ffc27cb41603_temperature:
      friendly_name: WCOG
    sensor.28_ff0dcf501603_temperature:
      friendly_name: ANKL
    sensor.28_ff5ad9501603_temperature:
      friendly_name: STUD
    sensor.28_ff4777b41603_temperature:
      friendly_name: GALE
    sensor.28_ffe302511603_temperature:
      friendly_name: BIBO
    sensor.28_ff380fb41603_temperature:
      friendly_name: WOHN
    sensor.28_ff9a3a501603_temperature:
      friendly_name: ARBE
    sensor.28_ffa9edb31605_temperature:
      friendly_name: FLUR
    sensor.28_ff5304511603_temperature:
      friendly_name: WCEG
    sensor.28_ffcbed531604_temperature:
      friendly_name: KUEC
    sensor.28_ff3b2a511603_temperature:
      friendly_name: KID1
    sensor.28_ff3bc3471603_temperature:
      friendly_name: SCHL
    sensor.28_ff0f3e541604_temperature:
      friendly_name: KID2