
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info

# Text to speech
tts:
  - platform: google_translate

# Test generic thermostat
climate: !include climate.yaml

# Python Script Integration aktivieren
python_script:

# https://www.home-assistant.io/integrations/rest_command/
# Nachfolgend ein Eintrag für die Testumgebung sowie die Produktivumgebung
rest_command:
  rollosteuerungtest:
    method: POST
    url: http://hwr.local:5000/Shutters
    payload: '{"cmd": "{{ cmd }}","window": "{{ window }}","time": "{{ time }}"}'
    content_type: 'application/json; charset=utf-8'
  rollosteuerung:
    method: POST
    url: http://localhost:5000/Shutters
    payload: '{"cmd": "{{ cmd }}","window": "{{ window }}","time": "{{ time }}"}'
    content_type: 'application/json; charset=utf-8'

# https://www.home-assistant.io/integrations/cover.template/
cover: !include cover.yaml

# Modul 1
#  name: ArbeitUp
#  name: ArbeitDown
#  name: WohnOstUp
#  name: WohnOstDown
#  name: WohnSuedUp
#  name: WohnSuedDown
#  name: WohnTuerUp
#  name: WohnTuerDown
# Modul 2
#  name: KuecheTuerUp
#  name: KuecheTuerDown
#  name: KuecheSuedUp
#  name: KuecheSuedDown
#  name: KuecheWestUp
#  name: KuecheWestDown
#  name: WCEGUp
#  name: WCEGDown
# Modul 3
#  name: HWRUp
#  name: HWRDown
#  name: TreppeUp
#  name: TreppeDown
#  name: MalteNordUp
#  name: MalteNordDown
#  name: MalteOstUp
#  name: MalteOstDown
# Modul 4
#  name: SinaOstUp
#  name: SinaOstDown
#  name: SinaSuedUp
#  name: SinaSuedDown
#  name: BiboUp
#  name: BiboDown
#  name: WCOGSuedUp
#  name: WCOGSuedDown
# Modul 5
#  name: WCOGWestUp
#  name: WCOGWestDown
#  name: SchlafenUp
#  name: SchlafenDown

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml

# Connect to Vitodens 300 with Vitotronic 200 via vicare integration
vicare:
  username: !secret vicare_user
  password: !secret vicare_pass
  client_id: !secret vicare_id
  name: ViCare

# Altes esersa Geraet
#    switch.29_ae571a000000_pio_0:
#      friendly_name: Erz_Arbeiten
#    switch.29_ae571a000000_pio_1:
#      friendly_name: Erz_Wohnen_Ecke
#    switch.29_ae571a000000_pio_2:
#      friendly_name: Erz_Kueche
#    switch.29_ae571a000000_pio_3:
#      friendly_name: Erz_Bibo
#    switch.29_ae571a000000_pio_4:
#      friendly_name: Erz_Schlafen
#    switch.29_ae571a000000_pio_5:
#      friendly_name: Erz_Galerie
#    switch.29_ae571a000000_pio_6:
#      friendly_name: Erz_Studio

# For connection to the cts-700 module from NILAN, which is part of my air
# ventilation system from Kermi, x-well N300 - CR300 with external control unit CTS700
modbus:
  - name: nilan
    type: tcp
    host: 192.168.178.234
    port: 502
    switches:
      - name: "NILAN Pause"
        unique_id: nilan_pause_mode
        slave: 1
        address: 4727
        command_on: 3
        command_off: 0
        verify:
            delay: 2
      - name: "NILAN System Off"
        unique_id: nilan_all_systems_stop
        slave: 1
        address: 4104
        command_on: 1
        command_off: 0
        verify:
            delay: 2
    sensors:
      - name: "NILAN Humidity"
        unique_id: nilan_humidity
        address: 4716
        unit_of_measurement: "%"
        slave: 1
      - name: "NILAN Aussenluftfuehler"
        unique_id: nilan_temperature_outdoor
        # T1
        unit_of_measurement: "°C"
        slave: 1
        address: 5152
        scale: 0.1
        precision: 1
        # count: 1
        # data_type: int
      - name: "NILAN Zuluftfuehler"
        unique_id: nilan_temperature_inlet
        # T2
        unit_of_measurement: "°C"
        slave: 1
        address: 5153
        scale: 0.1
        precision: 1
        # count: 1
        # data_type: int
      - name: "NILAN Abluftfuehler (Raumtemperatur)"
        unique_id: nilan_temperature_room
        # T3
        unit_of_measurement: "°C"
        slave: 1
        address: 5154
        scale: 0.1
        precision: 1
        # count: 1
        # data_type: int
      - name: "NILAN Fortluftfuehler (nach Waermetauscher)"
        unique_id: nilan_temperature_after_heatexchange
        # T4
        unit_of_measurement: "°C"
        slave: 1
        address: 5155
        scale: 0.1
        precision: 1
        # count: 1
        # data_type: int
      - name: "NILAN CO2 Sensor"
        unique_id: nilan_dev_co2_sensor
        # CO2
        unit_of_measurement: "%"
        slave: 1
        address: 4712
        # count: 1
        # data_type: int
      - name: "NILAN Bypass State"
        unique_id: nilan_dev_bypass1
        # Bypass
        unit_of_measurement: "%"
        slave: 1
        address: 4704
        # count: 1
      - name: "NILAN Leistung IN"
        unique_id: nilan_fan_speed_in
        unit_of_measurement: '%'
        slave: 1
        address: 4699
        # count: 1
      - name: "NILAN Leistung OUT"
        unique_id: nilan_fan_speed_out
        unit_of_measurement: '%'
        slave: 1
        address: 4700
        # count: 1
      - name: "NILAN Sollwert Lufttemperatur"
        unique_id: nilan_air_setpoint
        unit_of_measurement: '°C'
        slave: 1
        address: 4746
        # count: 1
        scale: 0.1
      - name: "NILAN Sollleistung"
        unique_id: nilan_fan_setpoint
        unit_of_measurement: '%'
        slave: 1
        address: 4747
        # count: 1
  - name: victron
    type: tcp
    host: 192.168.178.43
    port: 502
    sensors:
      - name: 'Victron Grid meter Energie L1'
        unique_id: victron_grid_l1_energy_from_net
        unit_of_measurement: "kWh"
        slave: 30
        address: 2603
        data_type: uint16
        scale: 0.01
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Grid meter Energie L2'
        unique_id: victron_grid_l2_energy_from_net
        unit_of_measurement: "kWh"
        slave: 30
        address: 2604
        data_type: uint16
        scale: 0.01
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Grid meter Energie L3'
        unique_id: victron_grid_l3_energy_from_net
        unit_of_measurement: "kWh"
        slave: 30
        address: 2605
        data_type: uint16
        scale: 0.01
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Grid meter Total ins Netz'
        unique_id: victron_grid_total_energy_to_net
        unit_of_measurement: "kWh"
        slave: 30
        address: 2636
        data_type: uint32
        scale: 0.01
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Grid meter Total aus Netz'
        unique_id: victron_grid_total_energy_from_net
        unit_of_measurement: "kWh"
        slave: 30
        address: 2634
        data_type: uint32
        scale: 0.01
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Solar Gesamteintrag'
        unique_id: victron_solar_user_yield
        unit_of_measurement: "kWh"
        slave: 238
        address: 790
        data_type: uint16
        scale: 0.1
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Solareintrag Dach'
        unique_id: victron_solar_user_yield_dach
        unit_of_measurement: "kWh"
        slave: 235
        address: 790
        data_type: uint16
        scale: 0.1
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Batterie'
        unique_id: victron_battery_state_of_charge
        unit_of_measurement: "%"
        slave: 100 # hub
        address: 843
        data_type: uint16
        scale: 1
        precision: 1
        scan_interval: 5
        device_class: battery
      - name: 'Victron Batteriespannung'
        unique_id: victron_battery_voltage
        unit_of_measurement: "V"
        slave: 100 # hub
        address: 840
        data_type: uint16
        scale: 0.1
        precision: 0
        scan_interval: 5
        device_class: voltage
      - name: 'Victron Batteriestrom (BMS)'
        unique_id: victron_battery_current
        unit_of_measurement: "A"
        slave: 1
        address: 261
        data_type: int16
        scale: 0.1
        precision: 1
        scan_interval: 5
        device_class: current
      - name: 'Victron Batterietemperatur (BMS)'
        unique_id: victron_battery_temperature
        unit_of_measurement: "°C"
        slave: 1
        address: 262
        data_type: int16
        scale: 0.1
        precision: 1
        scan_interval: 5
        device_class: temperature
      - name: 'Victron Batterie Gesamtentladung (BMS)'
        unique_id: victron_battery_discharged_energy
        unit_of_measurement: "kWh"
        slave: 1
        address: 301
        data_type: uint16
        scale: 0.1
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Batterie Gesamtladung (BMS)'
        unique_id: victron_battery_charged_energy
        unit_of_measurement: "kWh"
        slave: 1
        address: 302
        data_type: uint16
        scale: 0.1
        precision: 1
        scan_interval: 5
        device_class: energy
        state_class: total_increasing
      - name: 'Victron Ladeleistung'
        unique_id: victron_charger_power
        unit_of_measurement: "W"
        slave: 100 # hub
        address: 855
        data_type: uint16
        scale: 1
        precision: 1
        scan_interval: 5
        device_class: power
      - name: 'Victron Solar-Eintrag'
        unique_id: victron_pv_dc_coupled_power
        unit_of_measurement: "W"
        slave: 100 # hub
        address: 850
        data_type: uint16
        scale: 1
        precision: 1
        scan_interval: 5
        device_class: power

# Sensor mittels Statistik Integration wrappen
sensor:
  - platform: statistics
    name: "Garage Luftfeuchtigkeit"
    entity_id: sensor.26_00003824da00_humidity_htm1735
    sampling_size: 5
    state_characteristic: median
    max_age:
      minutes: 30
  - platform: statistics
    name: "Garage Temperatur"
    entity_id: sensor.26_00003824da00_temperature
    sampling_size: 5
    state_characteristic: median
    max_age:
      minutes: 30
  - platform: filter
    name: "Garage Gefilterte Luftfeuchtigkeit"
    entity_id: sensor.26_00003824da00_humidity_htm1735
    filters:
      - filter: range
        lower_bound: 0
        upper_bound: 100
      - filter: outlier
        window_size: 4
        radius: 8.0
      - filter: lowpass
        time_constant: 5
        precision: 1
  # Nutzt Template-Sensor, um Verbrauch aufzuakkumulieren (Batterieeintrag)
  - platform: integration
    name: Victron Batterieeintrag
    unique_id: victron_battery_energy_in
    source: sensor.victron_tmpl_battery_power_in
    method: left
  # Nutzt Template-Sensor, um Verbrauch aufzuakkumulieren (Batterienutzung)
  - platform: integration
    name: Victron Batterieaustrag
    unique_id: victron_battery_energy_out
    source: sensor.victron_tmpl_battery_power_out
    method: left
  - platform: command_line
    # delete old backups
    # flow: open backup folder & list files sorted by age -> delete first 3 entries (jungest files) from output -> run remove on each left
    name: delete old backups
    command: 'cd /config/backups/ && ls -A1t | sed -e "1,4d" | xargs rm'
    scan_interval: 3600

# Add "Lovelace Mini Graph Card"
# https://github.com/kalkih/mini-graph-card
#resources:
#  - url: /local/mini-graph-card-bundle.js?v=0.10.0
#    type: module

# Convert auto generated 1-Wire device ids into friendly names 
homeassistant:
  customize:
    switch.29_ad0837000000_pio_0:
      friendly_name: "Arbeitszimmer Fenster (11)"
    switch.29_ad0837000000_pio_1:
      friendly_name: "Wohnzimmer Ecke (13)"
    switch.29_ad0837000000_pio_2:
      friendly_name: "15 oder 16"
    switch.29_ad0837000000_pio_3:
      friendly_name: "Küche Terrassentür (18)"
    switch.29_ad0837000000_pio_4:
      friendly_name: "Malte Ost (21)"
    switch.29_ad0837000000_pio_5:
      friendly_name: "Malte Nord (22)"
    switch.29_ad0837000000_pio_6:
      friendly_name: "Bibliothek Fenster (30)"
    switch.29_ad0837000000_pio_7:
      friendly_name: "Sina Fenster Bibo (31)"
    switch.29_b20837000000_pio_0:
      friendly_name: "Sina Fenster Ecke (32)"
    switch.29_b20837000000_pio_1:
      friendly_name: "Schlafzimmer Fenster (33)"
    switch.29_b20837000000_pio_2:
      friendly_name: "Schlafzimmer Sven (34)"
    switch.29_b20837000000_pio_3:
      friendly_name: "Schlafzimmer Mandy (35)"
    switch.29_b20837000000_pio_4:
      friendly_name: "Gallerie Dachfenster (36)"
    switch.29_b20837000000_pio_5:
      friendly_name: "Gallerie Fenster (37)"
    switch.29_b20837000000_pio_6:
      friendly_name: "Studio Fenster (38)"
    switch.29_b20837000000_pio_7:
      friendly_name: "Zirkulationspumpe"
    switch.29_b90437000000_pio_0:
      friendly_name: FBH_ANKL
    switch.29_b90437000000_pio_1:
      friendly_name: FBH_KID2
    switch.29_b90437000000_pio_2:
      friendly_name: FBH_KID1
    switch.29_b90437000000_pio_3:
      friendly_name: FBH_SCHL
    switch.29_b90437000000_pio_4:
      friendly_name: FBH_GALE
    switch.29_b90437000000_pio_5:
      friendly_name: FBH_STUD
    switch.29_b90437000000_pio_6:
      friendly_name: FBH_WCEG_H
    switch.29_b90437000000_pio_7:
      friendly_name: FBH_WCOG_H  
    sensor.28_ffc27cb41603_temperature:
      friendly_name: WCOG
    sensor.28_ff0dcf501603_temperature:
      friendly_name: ANKL
    sensor.28_ff5ad9501603_temperature:
      friendly_name: STUD
    sensor.28_ff4777b41603_temperature:
      friendly_name: GALE
    sensor.28_ffe302511603_temperature:
      friendly_name: BIBO
    sensor.28_ff380fb41603_temperature:
      friendly_name: WOHN
    sensor.28_ff9a3a501603_temperature:
      friendly_name: ARBE
    sensor.28_ffa9edb31605_temperature:
      friendly_name: FLUR
    sensor.28_ff5304511603_temperature:
      friendly_name: WCEG
    sensor.28_ffcbed531604_temperature:
      friendly_name: KUEC
    sensor.28_ff3b2a511603_temperature:
      friendly_name: KID1
    sensor.28_ff3bc3471603_temperature:
      friendly_name: SCHL
    sensor.28_ff0f3e541604_temperature:
      friendly_name: KID2
    sensor.28_ff80ce501603_temperature:
      friendly_name: HWRA